import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { FaGoogle } from "react-icons/fa";

import firebase from "firebase/compat/app";
import "firebase/compat/auth";

import Navbar from "../components/Navbar"
import Hero from "../components/Hero"

import { Fragment } from "react";
import { Disclosure, Menu, Transition } from "@headlessui/react";
import { MenuIcon, XIcon } from "@heroicons/react/outline";

firebase.initializeApp({
  apiKey: "AIzaSyBMItaTJzYXdgQHrPDcTQhpVPZbjOtmNEo",
  authDomain: "borrow-a11e2.firebaseapp.com",
  projectId: "borrow-a11e2",
  storageBucket: "borrow-a11e2.appspot.com",
  messagingSenderId: "350280833320",
  appId: "1:350280833320:web:890ce9a0c2a5195104d81d",
  measurementId: "G-LNELFDBPC0",
});

import { useAuthState } from "react-firebase-hooks/auth";
import { useCollectionData } from "react-firebase-hooks/firestore";

const auth = firebase.auth();

export default function Home() {
  const [user] = useAuthState(auth);

  return (
    <div className={styles.container}>
      <Head>
        <title>Borrow - The College Sharing Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user ? <Dashboard /> : <SignIn />}
    </div>
  );
}

function SignIn() {
  const signInWithGoogle = () => {
    const provider = new firebase.auth.GoogleAuthProvider();
    auth.signInWithPopup(provider);
  };

  return (
    <div className="relative bg-white overflow-hidden h-screen	">
      <div className="max-w-7xl mx-auto">
        <div className="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:max-w-lg lg:w-full lg:pb-28 xl:pb-32">
          <main className="mt-10 mx-auto max-w-7xl lg:pt-40 px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
            <div className="sm:text-center lg:text-left">
              <h1 className="text-4xl tracking-tight font-extrabold text-pink-500 sm:text-5xl md:text-6xl">
                <span className="block xl:inline">Borrow</span>{" "}
              </h1>
              <p className="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
                Borrow is a sharing economy platform for College Students that
                reduces friction of lending everyday items. On the app, students
                will <span className="bg-yellow-100">share and lend items</span>{" "}
                such as textbooks, lab coats, sporting goods, or electronics.
              </p>
              <div className="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
                <div className="rounded-md mt-5 shadow">
                  <a
                    href="#"
                    onClick={signInWithGoogle}
                    className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-pink-500 bg-pink-100 hover:bg-pink-200 md:py-4 md:text-lg md:px-10"
                  >
                    <FaGoogle className="mr-2 " />
                    Sign in with Google
                  </a>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
      <div className="lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2">
        <img
          className="h-full w-full object-cover sm:h-72 md:h-96 lg:w-full lg:h-full"
          src="https://kiwienergy.us/wp-content/uploads/2022/01/iStock-1153885263.jpg"
          alt=""
        />
      </div>
    </div>
  );
}

function SignOut() {
  function classNames(...classes) {
    return classes.filter(Boolean).join(" ");
  }

  return (

    <>
    <Navbar/>
    <Hero/>
    </>


  
  );
}

function Dashboard() {
  return (
    <div>
      <SignOut />
    </div>
  );
}
